import './statics/of'
import './statics/error'
import './statics/fromPromise'

import './operators/catchError'
import './operators/distinctUntilChanged'
import './operators/tap'
import './operators/filter'
import './operators/map'
import './operators/mapTo'
import './operators/merge'
import './operators/startWith'
import './operators/switchMap'
import './operators/take'
import './operators/withLatestFrom'
import './operators/withValue'
